name: cry
description: 一个Flutter组件库，包含button、form、dataTable、dialog、imageUpload、root、toggleButton、transfer、treeTable
version: 0.1.5
homepage: http://www.cairuoyu.com/
publish_to: https://pub.dev
#publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^2.1.3
  intl: ^0.16.1
  image_picker: ^0.6.7
  image_picker_for_web: ^0.1.0
  dio: 3.0.7
  global_configuration: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
